info:
  contact:
    email: onix@gatblau.org
    name: gatblau
    url: http://onix.gatblau.org/
  description: Run Artisan packages with in a host
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Artisan Host Runner
  version: 0.0.4
paths: {}
swagger: "2.0"
