definitions:
  server.WebHookConfig:
    properties:
      actions:
        description: Actions that should trigger the webhook
        items:
          type: integer
        type: array
      group:
        description: the repository Group for the webhook
        type: string
      id:
        description: the unique webhook identifier
        type: string
      name:
        description: the repository Name for the webhook
        type: string
      pwd:
        description: the webhook URI password
        type: string
      uname:
        description: the webhook URI user
        type: string
      uri:
        description: the webhook URI
        type: string
    type: object
info:
  contact:
    email: onix@gatblau.org
    name: gatblau
    url: http://onix.gatblau.org/
  description: Registry for Artisan packages
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Artisan Package Registry
  version: 0.0.4
paths:
  /:
    get:
      description: |-
        Checks that the registry HTTP server is listening on the required port.
        Use a liveliness probe.
        It does not guarantee the server is ready to accept calls.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Check that the registry HTTP API is live
      tags:
      - General
  /file/{repository-group}/{repository-name}/{filename}:
    get:
      parameters:
      - description: the package repository group name
        in: path
        name: repository-group
        required: true
        type: string
      - description: the package repository name
        in: path
        name: repository-name
        required: true
        type: string
      - description: the filename to download
        in: path
        name: filename
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Download a file from the registry
      tags:
      - Files
  /package/{repository-group}/{repository-name}/tag/{package-tag}:
    delete:
      description: deletes the package file and its seal from the pre-configured backend
        (e.g. Nexus, etc)
      parameters:
      - description: the package repository group name
        in: path
        name: repository-group
        required: true
        type: string
      - description: the package repository name
        in: path
        name: repository-name
        required: true
        type: string
      - description: the package reference name
        in: path
        name: tag
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Delete a package from the configured backend
      tags:
      - Packages
    post:
      description: uploads the package file and its seal to the pre-configured backend
        (e.g. Nexus, etc)
      parameters:
      - description: the package repository group name
        in: path
        name: repository-group
        required: true
        type: string
      - description: the package repository name
        in: path
        name: repository-name
        required: true
        type: string
      - description: the package reference name
        in: path
        name: tag
        required: true
        type: string
      - description: the package metadata in JSON base64 encoded string format
        in: formData
        name: package-meta
        required: true
        type: string
      - description: the package file part of the multipart message
        in: formData
        name: package-file
        required: true
        type: file
      - description: the seal file part of the multipart message
        in: formData
        name: package-seal
        required: true
        type: file
      produces:
      - text/plain
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "423":
          description: Locked
          schema:
            type: string
      summary: Push a package to the configured backend
      tags:
      - Packages
  /package/info/{repository-group}/{repository-name}/id/{package-id}:
    delete:
      description: deletes the meta-data associated with the package identified by
        its id
      parameters:
      - description: the package repository group name
        in: path
        name: repository-group
        required: true
        type: string
      - description: the package repository name
        in: path
        name: repository-name
        required: true
        type: string
      - description: the package unique identifier
        in: path
        name: package-id
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            type: string
      summary: Delete the meta-data associated with the specified package
      tags:
      - Package Information
    get:
      consumes:
      - text/html
      - ' application/json'
      - ' application/yaml'
      - ' application/xml'
      - ' application/xhtml+xml'
      description: gets meta-data about the package identified by its id
      parameters:
      - description: the package repository group name
        in: path
        name: repository-group
        required: true
        type: string
      - description: the package repository name
        in: path
        name: repository-name
        required: true
        type: string
      - description: the package unique Id
        in: path
        name: package-id
        required: true
        type: string
      produces:
      - application/json
      - ' application/yaml'
      - ' application/xml'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get information about the specified package
      tags:
      - Package Information
    put:
      description: updates meta-data about the package identified by its id
      parameters:
      - description: the package repository group name
        in: path
        name: repository-group
        required: true
        type: string
      - description: the package repository name
        in: path
        name: repository-name
        required: true
        type: string
      - description: the package unique identifier
        in: path
        name: package-id
        required: true
        type: string
      - description: the package information to be updated
        in: body
        name: package-info
        required: true
        schema:
          type: object
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Update information about the specified package
      tags:
      - Package Information
  /package/manifest/{repository-group}/{repository-name}/{tag}:
    get:
      consumes:
      - text/html
      - ' application/json'
      - ' application/yaml'
      - ' application/xml'
      - ' application/xhtml+xml'
      description: gets the manifest associated with a specific package
      parameters:
      - description: the package repository group name
        in: path
        name: repository-group
        required: true
        type: string
      - description: the package repository name
        in: path
        name: repository-name
        required: true
        type: string
      - description: the package tag
        in: path
        name: tag
        required: true
        type: string
      produces:
      - application/json
      - ' application/yaml'
      - ' application/xml'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get manifest
      tags:
      - Package Information
  /repository:
    get:
      consumes:
      - text/html
      - ' application/json'
      - ' application/yaml'
      - ' application/xml'
      - ' application/xhtml+xml'
      description: gets meta-data about packages in the specified repository
      produces:
      - application/json
      - ' application/yaml'
      - ' application/xml'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get information about all repositories in the package registry
      tags:
      - Repository Information
  /repository/{repository-group}/{repository-name}:
    get:
      consumes:
      - text/html
      - ' application/json'
      - ' application/yaml'
      - ' application/xml'
      - ' application/xhtml+xml'
      description: gets meta-data about packages in the specified repository
      parameters:
      - description: the package repository group name
        in: path
        name: repository-group
        required: true
        type: string
      - description: the package repository name
        in: path
        name: repository-name
        required: true
        type: string
      produces:
      - application/json
      - ' application/yaml'
      - ' application/xml'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get information about the packages in a repository
      tags:
      - Repository Information
  /webhook/{repository-group}/{repository-name}:
    get:
      description: get a list of webhook configurations for the specified repository
      parameters:
      - description: the package repository group name
        in: path
        name: repository-group
        required: true
        type: string
      - description: the package repository name
        in: path
        name: repository-name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: get a list of webhooks
      tags:
      - Webhooks
    post:
      description: creates the webhook configuration for a specified repository and
        url
      parameters:
      - description: the package repository group name
        in: path
        name: repository-group
        required: true
        type: string
      - description: the package repository name
        in: path
        name: repository-name
        required: true
        type: string
      - description: the webhook configuration
        in: body
        name: package-info
        required: true
        schema:
          $ref: '#/definitions/server.WebHookConfig'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: creates a webhook configuration
      tags:
      - Webhooks
  /webhook/{repository-group}/{repository-name}/{webhook-id}:
    delete:
      description: delete the specified webhook configuration
      parameters:
      - description: the package repository group name
        in: path
        name: repository-group
        required: true
        type: string
      - description: the package repository name
        in: path
        name: repository-name
        required: true
        type: string
      - description: the webhook unique identifier
        in: path
        name: webhook-id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: delete a webhook configuration by Id
      tags:
      - Webhooks
swagger: "2.0"
