#!/bin/bash
# application 'Onix Config Manager' deploy script using docker-compose
# auto-generated by Artisan on 2022-06-01 15:52:30.100371 +0000 UTC

if ! command -v docker
then
  echo "docker is required but not installed"
  exit
fi
if ! command -v docker-compose 
then
  echo "docker-compose is required but not installed"
  exit
fi

# ensure attachable docker network is already created
if [ ! "$(docker network ls | grep onix_config_manager_network)" ]
then
  docker network create onix_config_manager_network
fi

# create docker volumes
docker volume create db

# launch docker containers
docker-compose up -d
