#!/bin/bash
# ox-app: updates the default admin password with the auto generated password provided by this manifest

# auto-generated by Artisan on 2022-06-01 15:52:30.100351 +0000 UTC


echo "updating Onix admin password from default ..."
art curl -X PUT \
  -a 25 \
  -u "admin:0n1x" \
  -H "Content-Type: application/json" \
  "http://ox-app":"8080"/user/"${OX_APP_WAPI_ADMIN_USER}"/pwd \
  -d "{\"pwd\":\"${OX_APP_WAPI_ADMIN_PWD}\"}"
