---
name: pgadmin-svc
description: db web client for postgresql
port: "9008"
var:
  - name: PGADMIN_DEFAULT_EMAIL
    description: the default user id which will be used to login to pgadmin web console
    value: "admin@local.com"
  - name: PGADMIN_DEFAULT_PASSWORD
    description: the password to authenticate user to pgadmin web console
    secret: true
    value: ${fx=pwd:16,false}
  - name: PGADMIN_LISTEN_PORT
    description: Force PGAdmin to listen on a specific port instead of default
    value: 9008
  - name: PGADMIN_SERVER_JSON_FILE
    description: Initial server entry
    value: "/pgadmin4/onix/postgres_servers.json"
  - name: PGADMIN_CONFIG_SERVER_MODE
    description: sets or unsets the container into server mode, i.e. login
    value: "False"
  - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
    description: disables the requirement for a master password (you still need database password)
    value: "False"
file:
  - path: /pgadmin4/onix/postgres_servers.json
    description: the configuration of event receivers used by pilotctl to send events
    template: |
      {
        "Servers": {
          "1": {
            "Name": "Main Onix database",
            "Group": "Onix",
            "Port": 5432,
            "Host": "${bind=db-svc}",
            "Username": "${bind=ox-svc:var:DB_ADMIN_USER}",            
            "MaintenanceDB": "postgres",
            "SSLMode": "disable"
          }
        }
      }
...