#
#    Onix Pilot Host Control Service
#    Copyright (c) 2018-2021 by www.gatblau.org
#    Licensed under the Apache License, Version 2.0 at http://www.apache.org/licenses/LICENSE-2.0
#    Contributors to this project, hereby assign copyright in this code to the project,
#    to be licensed under the same terms as the rest of the code.
#

#############################################################
# Important Notes - please read before bringing up the stack!
#############################################################
#
# This stack presumes that the databases in the "docker-compose.yaml" stack are up and running

version: '3'

services:

  mongo-express:
    image: mongo-express
    container_name: mongo-gui
    restart: always
    ports:
      - 8083:8081
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      #ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://evr-mongo-db:${PILOTCTL_EVR_MONGO_DBPORT}/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 8084:8084
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: QuB3vUL99gi8L8
      PGADMIN_LISTEN_PORT: 8084

#############################################################################
# Networking
#############################################################################
networks:
  default:
    name: ${DOCKER_NETWORK}
