---
name: nexus-app
description: Nexus 3 repository manager
port:
  http: "8081"
  docker-http: "5000"
  docker-https: "5001"
var:
  - name: NEXUS_ADMIN_PASSWORD
    description: the nexus admin password
    secret: true
    value: ${fx=pwd:16,false}
  - name: SETUP_DOCKER_REGISTRY
    description: Whether to setup docker registry with in Nexus.
    value: true    
volume:
  - name: nexus-data
    path: /nexus-data
init:
  - builder: compose
    scripts:
      - read_default_password
      - setup_nexus
scripts:
  - name: read_default_password
    description: |
      reads Nexus' default admin password from within the container's file system
      using docker exec command and writes the content to a temporary file
      note: this process should run outside of a container, as it needs to call the docker exec command
    content: |
      echo "waiting for nexus process to create default admin password, please wait..."
      DEFAULT_PWD=
      while [ -z "$DEFAULT_PWD" ]
      do
        sleep 1
        DEFAULT_PWD=$(docker exec ${bind=nexus-app} cat /nexus-data/admin.password 2>/dev/null)
      done
      echo $DEFAULT_PWD > temppwd
  - name: setup_nexus
    description: |
      updates the nexus default admin password, disables anonymous access and
      creates a hosted repository required by the artisan registry
      note: this process should run within a container attached to the application network
    runtime: ubi-min
    content: |
      DEFAULT_PWD=$(cat temppwd)
      echo "waiting for nexus to come online, ignore errors, please wait..."
      art curl -X GET \
        -a 25 \
        http://${bind=nexus-app}:${bind=nexus-app:port[http]}/service/rest/v1/status \
        -H 'accept: application/json'

      echo "updating admin password"
      art curl -X PUT \
        -u admin:${DEFAULT_PWD} \
        http://${bind=nexus-app}:${bind=nexus-app:port[http]}/service/rest/v1/security/users/admin/change-password \
        -H 'accept: application/json','Content-Type: text/plain' \
        -d "${bind=nexus-app:var:NEXUS_ADMIN_PASSWORD}"

      rm temppwd

      echo "disabling nexus anonymous access"
      art curl -X PUT \
        -u admin:${bind=nexus-app:var:NEXUS_ADMIN_PASSWORD} \
        http://${bind=nexus-app}:${bind=nexus-app:port[http]}/service/rest/v1/security/anonymous \
        -H 'accept: application/json','Content-Type: application/json' \
        -d '{"enabled": false}'
      
      if ${bind=nexus-app:var:SETUP_DOCKER_REGISTRY} ; then
        echo "creating new artisan docker registry in nexus"
        art curl -X POST \
          -u admin:${bind=nexus-app:var:NEXUS_ADMIN_PASSWORD} \
          http://${bind=nexus-app}:${bind=nexus-app:port[http]}/service/rest/v1/repositories/docker/hosted \
          -H 'accept: application/json','Content-Type: application/json' \
          -d '{
          "name": "aps-docker-registry",
          "online": true,
          "storage": {
            "blobStoreName": "default",
            "strictContentTypeValidation": true,
            "writePolicy": "allow"
          },
          "cleanup": {
            "policyNames": [
              "string"
            ]
          },
          "component": {
            "proprietaryComponents": true
          },
          "docker": {
            "v1Enabled": false,
            "forceBasicAuth": true,
            "httpPort": ${bind=nexus-app:port[docker-http]},
            "httpsPort": ${bind=nexus-app:port[docker-https]}
          }
        }'
      fi
...