---
name: pilotctl-app
description: control pilot instances managing remote devices
port: "8888"
var:
  - name: OX_PILOTCTL_DB_HOST
    description: the name of the database service host used by pilot control to store management data
    value: ${bind=db}
  - name: OX_PILOTCTL_DB_USER
    description: the username to authenticate with the database service
    value: pilotctl
  - name: OX_PILOTCTL_DB_PWD
    description: the password to authenticate with the database service
    secret: true
    value: ${fx=pwd:16,false}
  - name: OX_HTTP_PORT
    description: the port the http
    value: ${bind=pilotctl-app:port}
  - name: OX_WAPI_URI
    description: the URI of the Onix Web API service used by pilot control to store configuration data (must include port)
    value: http://${bind=ox-app}:${bind=ox-app:port}
  - name: OX_WAPI_USER
    description: the username to authenticate with the Onix Web API service
    value: ${bind=ox-app:var:WAPI_ADMIN_USER}
  - name: OX_WAPI_PWD
    description: the password to authenticate with the Onix Web API service
    secret: true
    value: ${bind=ox-app:var:WAPI_ADMIN_PWD}
  - name: OX_WAPI_INSECURE_SKIP_VERIFY
    description: skips verification of TLS certificate for the Onix Web API service
    value: "false"
  - name: OX_ART_REG_URI
    description: the URI of the Artisan registry service used by pilot control to look up automation packages
    value: http://${bind=artreg-app}:${bind=artreg-app:port}
  - name: OX_ART_REG_USER
    description: the username to authenticate with the Artisan Registry service
    value: ${bind=artreg-app:var:OXA_HTTP_UNAME}
  - name: OX_ART_REG_PWD
    description: the password to authenticate with the Artisan Registry service
    secret: true
    value: ${bind=nexus-app:var:NEXUS_ADMIN_PASSWORD}
  - name: PILOTCTL_ONIX_EMAIL
    description: Demo email for dashboard logon
    value: "demouser@onix.com"
  - name: PILOTCTL_ONIX_USER
    description: Demo user for dashboard logon
    value: "demouser"
  - name: PILOTCTL_ONIX_PWD
    description: Password for demouser dashboard logon
    secret: true
    value: ${fx=pwd:13,true}123
  - name: OX_ART_REG_PACKAGE_FILTER
    description: Filter for retrieving Artisan registry packages through pilotctl
    value: "aps/"    
file:
  - path: /keys/.pilot_verify.pgp
    description: the public pgp key used by pilot to verify connections to pilot control
    secret: true
    content: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      Version: golang.org/x/crypto/openpgp - artisan-0.0.4-170521113707871-73bd30cf06-beta
      Comment: Cipher: AES128, Hash: SHA-256, RSA Bits: 2048, Created: 2021-05-21 15:44:00.02529 +0100 BST m=+0.294621441
      Hash: AES128/SHA-256

      xsBNBGCnxy8BCAC6D555PF+UPXnGVn6tGqtMypA7YnqAUuVPhwCK0IO8cO3F3rUu
      DJqx+g58Y7t0pKgzDiVt0c3kOL2CcBOwu5VFA8jSR3LS9VO6WXTBI/EwfyShl3JQ
      7KfhjvWzHS4UPvrhmm8PGKH4vxZXgVmZ/ZopIetG6TPuQRw5hBBUiTt1p9ZjitVA
      JQ+fYZ40dl/SUfzCpJHX0awwcIO1uyPSNIxbjxMqCvoKEjEwvyz5rwzP+zTIQ+7U
      K2rwKquXfErTfzgF5KNVANTnnfmXJEp27xjnfxjoWrrKtEorqvNhc5o1pZJ02kxA
      osECD9exCzWCd85FXUFhYv6c+RPcTBCsaNuNABEBAAHNlXJvb3QtQW5kcmVzcy1N
      YWNCb29rLVByby0yLmxvY2FsICgyMDQ4IGtleXMsIGdlbmVyYXRlZCBvbiAyMDIx
      LTA1LTIxIDE1OjQzOjU5LjczNTYzNSArMDEwMCBCU1QgbT0rMC4wMDQ5Njc2MjEp
      IDx0ZXN0QEFuZHJlc3MtTWFjQm9vay1Qcm8tMi5sb2NhbC5jb20+wsBiBBMBCAAW
      BQJgp8cvCRBsX5GA3AvitgIbAwIZAQAA4qkIAB8DBvCnIdhZ5hNJhn8j44ld4KoB
      dzr+EX0kXHcpUsdIO4famT/RS8Ej+iqQK4uTl0Q4zKOXx2LqhnsgLWme/1YlCUHe
      psqEyoPlPvSs9GWUzQOWKDfJTE7lW3kq4oGzvF/cdsMxLxVaC5AqcqGXvK2/TAd8
      m/DuYrvNULUNqI8X6whuuOlrqVuggwVb9fflG1xXrfWpRG3+49z/CMTV0IN5raFk
      wGW29IoBlvGLXdrQRZwTGTL0VbUFn7nCo5OnJ9ku8fzSTr9nN+bjl8Ga0XgeZgRp
      ymdQdYLDwjj+PaQTNjaiscZp4KSL0uTRX/2ARWrSlGuSfqmJkqOa/s/yPWjOwE0E
      YKfHLwEIAN+vRNerDdsRaTuhR+MnhkLXWVtHYClV9LpCFTgNYUR3EBdmK9UyqnmH
      VNodJXUBBSsriJc9UHg2hv/QymFMCuXJG499SS5naO51YCKidlv6dtkNot70PYvP
      Yr+JhPEyasC50SU8JNM5lLJ7unKTxUUvexaE2y08RFq/f03fxPi5G5pp2tkM9c/h
      2wgFnAhQX+kNSERIuS6YVPAio9Qy5QELUBlOSW7QvOli+weSNUaZSsiuN72Savsv
      O+puMhl0iGLCs04lPdTuptbikIY9WASBpJ6aaciYCb66g0kFUarBTvhafSipNGVp
      OMeerEn85axVYIKIfXFJG/PJIgJQew0AEQEAAcLAXwQYAQgAEwUCYKfHLwkQbF+R
      gNwL4rYCGwwAAG1RCACCEsqeffEXwFrsgm7MgeNU/A4WbLJ9OCeRhTYVljVXmUQz
      PDZ1odeZUAPLk+8fo1+WpKVdvWOpSpqyRtdBcByu+oshgOuxUI/KF/czRaL6jxdB
      UZtInZCijnui6MVUqVfB2AkVJTeHeYtnHnfDbUa3YRlKwJFkyl3FPxpUfdUksdFE
      9t+PkFd/3tExioYcj04kuDxaqhBxwXQtFscAeAgLNZ4nMN+Fp6jVjeizApIQ49Aa
      uFqdMLx/GXIiAWEL/0KULpj+wJ+Gn8wgeeSy9VoXbB/a1/U2Q7Rvmx2DpdlzSxpH
      d0rVSPxEiBWQLTbnGe4ujgqNcZNUrYaBZEdYW5y4
      =C7nB
      -----END PGP PUBLIC KEY BLOCK-----
  - path: /keys/.pilot_sign.pgp
    description: the private pgp key used by pilot to sign commands issued to pilot instances
    secret: true
    content: |
      -----BEGIN PGP PRIVATE KEY BLOCK-----
      Version: golang.org/x/crypto/openpgp - artisan-0.0.4-050821151730979-a187215ee8-beta
      Comment: Cipher: AES128, Hash: SHA-256, RSA Bits: 2048, Created: 2021-08-06 13:31:33.530099 +0100 BST m=+0.241912185
      Hash: AES128/SHA-256

      xcLYBGENK6UBCADAe4mMQmwjq+uV7XAPxAF42Yn2iJH2Vxv6Iv3v1z1/rZL1NHJg
      lgbj8qdqNP+jwA+6sjHt0owmGi7TmXTKCZ6wv8GQ7UfQICCWPP60CC9ycGeh3pqX
      3/kkNkkjOCcugDd414xKyNzOqvGf9htPiMpQxj3rzHrOC8Jfbs7XV1Kkv+s7TvCT
      3hOgJZoQ4115gkS9MrSfc11uQ+ExoQMDKN45T0y65K3hXmvoBOlGL6V3QoXpbDsp
      tVejhGzvGam20EHKyjtDpAHPA16r5ywS/pfp36PD+ExSCacOLwC5A8cPemLFQEho
      pYkO2T4YQZuWFsffI1MYkiZbNGtChOFHfqm3ABEBAAEAB/9fSQineX5FDmd6eece
      tt4vsCke9S6kryy3YDkrUPctzIRShJsWe05/63C7H+9pZbujpXEYFUGx3wZNU8s/
      9REs2FB/aSdCvZTEKv+/qcmrMj/rHuKSyppwNbtxBuxGlcxgMvxNTTAZ0v/4OwH8
      FnBpGiovH7OvapzXV2hnq9/KlCd1AKD4Y7NXXrEGXp45+/IJajZGUp76o+Q2zLun
      1MNB6hwavGX+Hrmr7GdW7IZL562VGiv5/dIJ8omf7CbVoLLbP62hIqVCIIEkfEdb
      WPIa/hvBuT9UMdCR9YkY5KgLp8wJAHBepVGR0mRra6qJgD/rojJBP8VjUeluOk6C
      YQxZBADmcQz/3LHbOFdoom+/gUEQx433W5wPrf/jP+oHqNvM8MaYDFz6+Fl5SCAQ
      3kQOKqwAKj+WD1cMu5E1uJDEL+prgzzYc81BVYkftOOmt90GK9ow35VY6KOm6PCB
      VYE5GTYW+NLAnYdwRsUUNOdm+vTpK26/+kBQTvUPPiOgDUF12wQA1dS2UD+ziIMP
      VAYpiKz7vYxEsAEaDqN/NJUP1gx0k2ubBSUj2e8Q3Uxy0l3ugD8ykv9B2Mc/pwxe
      iI4lzGWIDS8QIwpKneAVPfiCegUYg9jdLSOde+0iMnVx69gG5BhXIDozTTQvfoYg
      yXThilBqln6ZgJpq4Fo6wtctARYCGFUEAJKrVJAUG2WIBG2gyZb9hdQStQLkaUTj
      A9PYbA/t6KlSL+AuygMJFk4c6QI/QshZb/ihSEo43OfrwEfnV0wSoJOGpKyH7vBG
      pHQWK+JX6/OY5AeAQS3xKZTztSG6PSH7awgFgVY1TCcTK1hdp5Rw/kfuwdhlfGzN
      Sxf/x4bnW7EWNp7NSmFwcy5jdHJsLXBsYW5lIChrZXlzIGZvciBBUFMgRWRnZSBD
      b250cm9sIFBsYW5lKSA8YXBzLmN0cmwtcGxhbmVAYXRvcy5uZXQ+wsBoBBMBCAAc
      BQJhDSulCRBLhv7gwO6TmgIbAwIZAQILBwIVCAAAHNQIAGRMl/+Farw+5XsehJ3C
      gk8WT2Oi7uXi1YDUPwV+c7QcL9WIUhtRE2L8VcZOKstdO6bywp93LMQt9FZ+7Fnh
      TFtXuWLewYRbfgjr+wQD7eOFqsgrad9EIjBYa7cjceaCW8gSmR7If7vVigC5APV0
      0CZmrU4o4npW2vwqs5yDWekyxNJbCpS7Qpo3JIQlUU9nkh8JmZWHKMOJlg50f2gg
      A7pORba8f0/pnCwllHYbuOZM1RHDNUQOb9uEDqkWWm7vtfaI/6SfXCeNc/X/va+y
      ozcZZLyKunAjLCCi+OPDgf0Lg43HPqeY9MRODRzmfJ/vD1FjAHU+fR4oFKxocGPr
      MiLHwtgEYQ0rpQEIALhB879yR5mDztWozAU70pHozpFOkpE1l9YZZKwwraMYHyzT
      2H4WVjYeb5FP7Vcyp1QC0koR3TOA4FByYJlMqlVaEOqIdJMkv26/nIImOxUzozmU
      2DgPPt1lRAWN9hevspENHnixy9S6qpcI+PgzamtKDNT9o8R8n0uxb9H4+lAbU0d+
      fRH86jDN13jitbRMptYe49es+zBy7SkjHYFn4Db3IBk7Xbld2PTyatRVN3hGsyu5
      TOUcHMjy/tj6TxoZ2l1r1qlla6i6S1DE3kDKJQwgcAoNlU9remhJfLjTkZ++q8zR
      wOMuPejbV7qbVJlQc8h/XKJCqajUiQ0kplYI1BMAEQEAAQAIAIgp/OYanrzcwgn0
      zqiDd+3pvFV3WirDDyzh4Rq6cmbXWZp4B0HOYfFmdo5NIZjRzwPvfdXM88mu0JXC
      oI5JMIsYnu2i33spqeo+4Xrwo7LcUSApVcu/wHY98pGkQhto9K3qov0QbxAKziwF
      Lm/FFzyoIWl48wAuFE4MlxT1SI3PEo1fLEOJw3xAkJsy97bz55MhN5YEuQsKYL9E
      8Jj2u3y2xjiK3eiiqHi099DyhZIkPHy4ycxsW7K2TkTtCoUMEHKKPiIrg2AXus8O
      qtR4VM17u4vQnYjxFHUWtZOQed6yxT4feGlFuz9lBqxjQuVbemf4VCSMImXa1vzY
      TUMvYZEEANLncTn5iifflNpqZfv51XlvSA+XPv/4zEedYfrimhxDRY0b07d31Hyx
      KucWzMnevP+HaG++u7sJWxg2d9y6Xuo0iAl/Q/LxUwWu4bvRIxloXGGMgCm06uYs
      CEVRqigmEjjAl2o/QFyM8JhsnT30LMs+dlTuzdQbBaZnBOl2bhVZBADfp+zck9t7
      i2+GCTAPR9aRlFCLBnfpw8LlPhXjvB4SP8mkHqRYPpWEcNQY9gAGA6srJSGOz+uC
      tfJWRBC1VbtHcojDvNjkxw3ngLHa3V7YJU8jZgDFo92WTR7/WaPmMcmmHB5k/is5
      siN+++c/KHLr1ic47dDzi8hLcWazNVPLSwQAlVwRP8ua9IUCtqryshE3SxIN+8zw
      75o79pJYqn7g6OflLtftZ9YEIzdbwAku3Zl7uTrlkjNIo//hSNg5Vy/Llk5wiBRD
      rlPkBWkycR1HN9odh581gr4qUkBDgMgGUiKe6ph5AF5VFw7Chp9dKM1kHFWqzYtn
      I0CyzrZXh86pdRFDx8LAXwQYAQgAEwUCYQ0rpQkQS4b+4MDuk5oCGwwAAD5pCAAm
      nDSXHyuT+laP9jkxnqNkuFEeIGQJKBQ0JivZeUphg/SHGL1Im+cl+A7mDj0RT57c
      fF6kySAoccZnBJVrvvrSzdfgOdxO5nvx80OHUVgaRpU3opulnOyLWV891/SISqwB
      p9EjqZVr5pTuc6KNSgmwiMfOrMF13Ueg0hP199eVvVscQOK9xqW+N8a6UZSPc/Fj
      a+zpQmDYI9gboPz/hD/D1kB4gD0M+xtJZuCIHvG0o+4lZJUETDF+IE6Njv22zbfc
      0ZuRG8Ki5S2weqVHgUzOfhby/nhqEA/mZuRLHxxz1sW8XiYp9AIka0RvFKhSBWha
      Ov6TlWNQmb3ZFW4/B/sl
      =f8fo
      -----END PGP PRIVATE KEY BLOCK-----
  - path: /conf/ev_receive.json
    description: the configuration of event receivers used by pilotctl to send events
    template: |
      {
        "event_receivers": [
          {{ $count := 0 }}{{ if service "evr-mongo-app" }}{
            "uri": "${bind=evr-mongo-app}:${bind=evr-mongo-app:port}/events",
            "user": "${bind=evr-mongo-app:var:OX_HTTP_UNAME}",
            "pwd": "${bind=evr-mongo-app:var:OX_HTTP_PWD}"{{ $count := plus $count 1 }}
          }{{ end }}{{ if gt $count 1 }},{{ end }}
        ]
      }      
db:
  name: pilotctl
  app_version: 0.0.4
  host: ${bind=db}
  port: 5432
  provider: _pgsql
  user: ${bind=pilotctl-app:var:OX_PILOTCTL_DB_USER}
  pwd: ${bind=pilotctl-app:var:OX_PILOTCTL_DB_PWD}
  admin_user: postgres
  admin_pwd: ${bind=db:var:POSTGRES_PASSWORD}
  schema_uri: ${bind=pilotctl-app:schema_uri}
init:	
  - builder: compose	
    scripts:	
      - create_pilotctl_user  
scripts:
  - name: create_pilotctl_user
    description: |
      creates the main pilotctl user in Onix
    runtime: ubi-min
    content: |
      echo "creating pilotctl user ..."
      art curl -X PUT \
        -u "${bind=ox-app:var:WAPI_ADMIN_USER}:${bind=ox-app:var:WAPI_ADMIN_PWD}" \
        -H 'Content-Type: application/json' \
        "http://${bind=ox-app}":"${bind=ox-app:port}"/user/ONIX_PILOTCTL?notify=false \
        -d "{\"email\":\"${bind=pilotctl-app:var:PILOTCTL_ONIX_EMAIL}\", \"name\":\"${bind=pilotctl-app:var:PILOTCTL_ONIX_USER}\", \"pwd\":\"${bind=pilotctl-app:var:PILOTCTL_ONIX_PWD}\", \"service\":\"false\", \"acl\":\"*:*:*\"}"
...