---
labels:
  author: onix@gatblau.org
  application: Onix Artisan Command Line Interface
  description: The DevOps command line interface
  architecture: AMD64

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  REPO_NAME: quay.io/gatblau
  # the application version
  APP_VERSION: 0.0.4
  # a unique build number
  BUILD_VERSION: ${APP_VERSION}-${ARTISAN_REF}

profiles:
  - name: linux
    default: true
    application: artisan
    type: content/binary
    license: Apache Version 2
    labels:
      platform: linux
    env:
      GOOS: linux
    run:
      - $(build-linux)
    target: bin/linux/amd64/art

  - name: mac
    application: artisan
    type: content/binary
    license: Apache Version 2
    labels:
      platform: darwin
    env:
      GOOS: darwin
    run:
      - $(build-mac)
    target: bin/darwin/amd64/art

  - name: windows
    application: artisan
    type: content/binary
    env:
      GOOS: windows
    run:
      - $(build-win)
    target: bin/windows/art.exe

functions:
  - name: build-mac
    description: builds the Artisan CLI for MacOS
    env:
      GOOS: darwin
    run:
      - go build -ldflags="-X 'github.com/gatblau/onix/artisan/core.Version=${BUILD_VERSION} (community)'" -o bin/${GOOS}/${GOARCH}/art -v

  - name: build-mac-new
    description: builds the Artisan CLI for MacOS
    env:
      GOOS: darwin
      GOARCH: arm64
    run:
      - go build -ldflags="-X 'github.com/gatblau/onix/artisan/core.Version=${BUILD_VERSION} (community)'" -o bin/${GOOS}/${GOARCH}/art -v

  - name: build-linux
    description: builds the Artisan CLI for the linux platform
    env:
      GOOS: linux
    run:
      - go build -ldflags="-X 'github.com/gatblau/onix/artisan/core.Version=${BUILD_VERSION} (community)'" -o bin/${GOOS}/${GOARCH}/art -v

  - name: build-win
    description: builds the Artisan CLI for the linux platform
    env:
      GOOS: windows
    run:
      - go build -ldflags="-X 'github.com/gatblau/onix/artisan/core.Version=${BUILD_VERSION} (community)'" -o bin/${GOOS}/${GOARCH}/art -v

  - name: zip
    run:
      - zip art.zip bin/windows/amd64/art.exe bin/linux/amd64/art bin/darwin/amd64/art bin/darwin/arm64/art

  - name: tar
    run:
      - tar -zcvf art_linux_amd64.tar.gz -C bin/linux/amd64 .
      - tar -zcvf art_darwin_amd64.tar.gz -C bin/darwin/amd64 .
      - tar -zcvf art_darwin_arm64.tar.gz -C bin/darwin/arm64 .

  - name: build-all
    description: creates zip files with the cli binaries for the different platforms
    run:
      - $(build-linux)
      - $(build-mac)
      - $(build-mac-new)

  - name: release-bin
    description: creates zip files with the cli binaries for the different platforms
    run:
      - $(build-linux)
      - $(build-mac)
      - $(build-mac-new)
#      - $(build-win)
      - ./owner.sh
#      - zip -r -j art_win_amd64.zip bin/windows/art.exe
...