---
labels:
  author: onix@gatblau.org
  application: Onix Artisan Command Line Interface
  description: The DevOps command line interface
  architecture: AMD64

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  REPO_NAME: quay.io/gatblau
  # the application version
  APP_VERSION: 0.0.4
  # a unique build number
  BUILD_VERSION: ${APP_VERSION}-${ARTISAN_REF}

profiles:
  - name: linux
    default: true
    application: artisan
    type: content/binary
    license: Apache Version 2
    labels:
      platform: linux
    env:
      GOOS: linux
    run:
      - $(build-linux)
    target: bin/linux/art

  - name: windows
    application: artisan
    type: content/binary
    env:
      GOOS: windows
    run:
      - $(build-win)
    target: bin/windows/art.exe

functions:
  - name: build-mac
    description: builds the Artisan CLI for MacOS
    env:
      GOOS: darwin
    run:
      - go build -ldflags="-X 'github.com/gatblau/onix/artisan/core.Version=${BUILD_VERSION}'" -o bin/darwin/art -v

  - name: build-linux
    description: builds the Artisan CLI for the linux platform
    env:
      GOOS: linux
    run:
      - go build -ldflags="-X 'github.com/gatblau/onix/artisan/core.Version=${BUILD_VERSION}'" -o bin/linux/art -v

  - name: build-win
    description: builds the Artisan CLI for the linux platform
    env:
      GOOS: windows
    run:
      - go build -ldflags="-X 'github.com/gatblau/onix/artisan/core.Version=${BUILD_VERSION}'" -o bin/windows/art.exe -v

  - name: zip
    run:
      - zip art.zip bin/windows/art.exe bin/linux/art bin/darwin/art

  - name: release-bin
    description: creates zip files with the cli binaries for the different platforms
    run:
      - $(build-linux)
      - $(build-mac)
      - $(build-win)
      - tar -zcvf art_linux.tar.gz -C bin/linux .
      - tar -zcvf art_darwin.tar.gz -C bin/darwin .
      - zip -r -j art_win.zip bin/windows/art.exe
...