---
labels:
  author: onix@gatblau.org
  application: Onix Artisan Command Line Interface
  description: Package manager that build, package, sign and publish packages; and execute package  functions.
  architecture: amd64

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  REPO_NAME: quay.io/gatblau
  APP_VERSION: 0.0.4
  LIFECYCLE_STAGE: alpha

profiles:
  - name: linux
    default: true
    application: artisan
    artefact: gatblau/artisan
    type: content/binary
    license: Apache Version 2
    labels:
      platform: linux
    env:
      GOOS: linux
    run:
      - $(build-linux)
    target: bin/linux/art

  - name: windows
    application: artisan
    type: content/binary
    env:
      GOOS: windows
    run:
      - $(build-win)
    target: bin/windows/art.exe

functions:
  - name: set-version
    description: set-version on the parent build, updating global version
    run:
      - art run set-version ../

  - name: build-mac
    description: builds the Artisan CLI for MacOS
    env:
      GOOS: darwin
    run:
      - $(set-version)
      - go build -o bin/darwin/art -v

  - name: build-linux
    description: builds the Artisan CLI for the linux platform
    env:
      GOOS: linux
    run:
      - $(set-version)
      - go build -o bin/linux/art -v

  - name: build-win
    description: builds the Artisan CLI for the linux platform
    env:
      GOOS: windows
    run:
      - $(set-version)
      - go build -o bin/windows/art.exe -v

  - name: zip
    run:
      - zip art.zip bin/windows/art.exe bin/linux/art bin/darwin/art
...