#
# pilot - Copyright (c) 2019 by www.gatblau.org
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied.
# See the License for the specific language governing permissions and limitations under the License.
#
# Contributors to this project, hereby assign copyright in this code to the project,
# to be licensed under the same terms as the rest of the code.
#
# NOTE: This vagrant box facilitates development
#
# How to use:
#   $ vagrant up
#   $ vagrant ssh
#


############################################################
# Change the following as required to suit your requirements
VM_NAME="dev"
VM_MEM=4096
VM_CPU=8
############################################################


$SCRIPT = <<SCRIPT
clear
echo ================================================================
echo Updating and upgrading base install ...
sudo apt update && sudo apt upgrade -y
echo ================================================================
echo Installing additional tools ...
sudo apt install -y git docker.io docker-compose gnupg
sudo usermod -aG docker vagrant
echo ================================================================
echo Installing Kubernetes and Tekton CLI ...
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
rm kubectl
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3EFE0E0A2F2F60AA
echo "deb http://ppa.launchpad.net/tektoncd/cli/ubuntu focal main"|sudo tee /etc/apt/sources.list.d/tektoncd-ubuntu-cli.list
sudo apt update && sudo apt install -y tektoncd-cli
echo ================================================================
echo Adding OpenShift CLI ...
curl -O https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz
sudo tar xvf openshift-client-linux.tar.gz -C /usr/local/bin/ oc
rm openshift-client-linux.tar.gz
echo ================================================================
echo Adding Kustomize ...
curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
sudo install -o root -g root -m 0755 kustomize /usr/local/bin/kustomize
rm kustomize
echo ================================================================
echo Adding Helm ...
curl -s "https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3" | bash
echo ================================================================
echo Cleaning up ...
sudo apt -y autoremove
echo ================================================================
echo Finished - use "vagrant ssh" to connect
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.hostname = VM_NAME
  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.memory = VM_MEM
    v.cpus = VM_CPU
    v.gui = true
  end
  config.vm.network "forwarded_port", guest: 80, host: 8080, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 443, host: 8081, protocol: "tcp"
  config.vm.provision "shell", inline: $SCRIPT
end
