// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "gatblau",
            "url": "http://onix.gatblau.org/",
            "email": "onix@gatblau.org"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Checks that Artie's HTTP server is listening on the required port.\nUse a liveliness probe.\nIt does not guarantee the server is ready to accept calls.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "General"
                ],
                "summary": "Check that Artie's HTTP API is live",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/registry/{repository-group}/{repository-name}/{artefact-ref}": {
            "post": {
                "description": "uploads the artefact file and its seal to the pre-configured backend (e.g. Nexus, etc)",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Artefacts"
                ],
                "summary": "Push an artefact to the configured backend",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the artefact repository group name",
                        "name": "repository-group",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the artefact repository name",
                        "name": "repository-name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the artefact reference name",
                        "name": "artefact-ref",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "the artefact file part of the multipart message",
                        "name": "artefact-file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "the seal file part of the multipart message",
                        "name": "artefact-seal",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "423": {
                        "description": "Locked",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.4",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Artie: the generic artefact manager API",
	Description: "Artie's HTTP API for artefact backends.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
