---
labels:
  author: onix@gatblau.org
  application: Artisan's Doorman
  description: Distribution agent for Artisan packages.
  architecture: amd64

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  REPO_NAME: quay.io/gatblau
  ART_DOORMAN: artisan-doorman
  APP_VERSION: 0.0.4
  BUILD_VERSION: "version: ${APP_VERSION}-${ARTISAN_REF} (community)"

functions:
  - name: build-linux
    description: builds Doorman for Linux
    env:
      GOOS: linux
    run:
      - go build -ldflags="-X 'github.com/gatblau/onix/artisan/doorman/core.Version=${BUILD_VERSION}'" -o bin/linux/doorman -v

  - name: build-mac
    description: builds Doorman for MacOS
    env:
      GOOS: darwin
    run:
      - go build -ldflags="-X 'github.com/gatblau/onix/artisan/doorman/core.Version=${BUILD_VERSION}'" -o bin/darwin/doorman -v

  - name: swagen
    description: generates/refreshes the OpenAPI specifications for Doorman HTTP API
    run:
      - swag init -d ./ -g handlers.go --parseDependency types/*.go
        
  - name: build
    description: builds a Doorman image
    run:
      - $(build-linux)
      - docker build -t ${REPO_NAME}/${ART_DOORMAN}:${BUILD_VERSION} .
      - docker tag ${REPO_NAME}/${ART_DOORMAN}:${BUILD_VERSION} ${REPO_NAME}/${ART_DOORMAN}:latest

  - name: publish
    description: builds and publishes the Doorman image
    run:
      - $(build-linux)
      - docker build -t ${REPO_NAME}/${ART_DOORMAN}:${BUILD_VERSION} .
      - docker tag ${REPO_NAME}/${ART_DOORMAN}:${BUILD_VERSION} ${REPO_NAME}/${ART_DOORMAN}:latest
      - docker push ${REPO_NAME}/${ART_DOORMAN}:${BUILD_VERSION}
      - docker push ${REPO_NAME}/${ART_DOORMAN}:latest

  - name: debug
    description: starts doorman container using sleep infinity command
    run:
      - docker run --name doorman -itd quay.io/gatblau/artisan-doorman sleep infinity
...