---
env:
  APP_VERSION: 0.0.4

labels:
  author: gatblau
  application: Onix Host Pilot
  description: configuration management agent for server hosts
  architecture: amd64

functions:
  - name: set-version
    description: set-version on the parent build, updating global version
    run:
      - sh version.sh ${APP_VERSION}-${ARTISAN_REF}

  - name: build-linux
    description: builds the host pilot binary for the linux platform
    env:
      GOOS: linux
    run:
      - $(set-version)
      - go build -o bin/linux/pilot -v

  - name: build-windows
    description: builds the host pilot binary for the windows platform
    env:
      GOOS: windows
    run:
      - $(set-version)
      - go build -o bin/windows/pilot.exe -v

  - name: build-mac
    description: builds the host pilot binary for the macos platform
    env:
      GOOS: darwin
    run:
      - $(set-version)
      - go build -o bin/darwin/pilot -v

profiles:
  - name: linux
    default: true
    type: content/binary
    license: Apache Version 2
    run:
      - $(build-linux)
    target: bin/linux

  - name: mac
    default: true
    type: content/binary
    license: Apache Version 2
    run:
      - $(build-mac)
    target: bin/darwin

  - name: windows
    type: content/binary
    license: Apache Version 2
    run:
      - $(build-windows)
    target: bin/windows
...