---
env:
  # the application version
  APP_VERSION: 0.0.4
  # a unique build number
  BUILD_VERSION: ${APP_VERSION}-${ARTISAN_REF}

labels:
  author: gatblau.org
  application: Pilot
  product: Onix Configuration Manager
  description: Onix agent for managing remote host configuration
  architecture: AMD64

functions:
  - name: build-linux
    description: builds the host pilot binary for the linux platform
    env:
      GOOS: linux
    run:
      - go build -ldflags="-X 'github.com/gatblau/onix/piloth/core.Version=${BUILD_VERSION}'" -o bin/linux/pilot -v

  - name: build-windows
    description: builds the host pilot binary for the windows platform
    env:
      GOOS: windows
    run:
      - go build -ldflags="-X 'github.com/gatblau/onix/piloth/core.Version=${BUILD_VERSION}'" -o bin/windows/pilot -v

  - name: build-mac
    description: builds the host pilot binary for the macos platform
    env:
      GOOS: darwin
    run:
      - go build -ldflags="-X 'github.com/gatblau/onix/piloth/core.Version=${BUILD_VERSION}'" -o bin/darwin/pilot -v

  - name: build-arm
    description: builds the host pilot binary for the linux platform
    env:
      GOOS: linux
      GOARCH: arm
      GOARM: 5
    run:
      - go build -ldflags="-X 'github.com/gatblau/onix/piloth/core.Version=${BUILD_VERSION}'" -o bin/arm/pilot -v

profiles:
  - name: linux
    default: true
    type: content/binary
    license: Apache Version 2
    run:
      - $(build-linux)
    target: bin/linux

  - name: mac
    default: true
    type: content/binary
    license: Apache Version 2
    run:
      - $(build-mac)
    target: bin/darwin

  - name: windows
    type: content/binary
    license: Apache Version 2
    run:
      - $(build-windows)
    target: bin/windows
...