---
env:
  APP_VERSION: 0.0.4

labels:
  author: gatblau
  application: Onix Host Pilot
  description: configuration management agent for server hosts
  architecture: amd64

functions:
  - name: set-version
    description: set-version on the parent build, updating global version
    run:
      - sh version.sh ${APP_VERSION}-${ARTISAN_REF}

  - name: build-linux
    description: builds the host pilot binary for the linux platform
    env:
      GOOS: linux
    run:
      - $(set-version)
      - go build -o bin/pilot -v

  - name: build-windows
    description: builds the host pilot binary for the windows platform
    env:
      GOOS: windows
    run:
      - $(set-version)
      - go build -o bin/win/pilot.exe -v

profiles:
  - name: linux
    default: true
    type: content/binary
    license: Apache Version 2
    run:
      - $(build-linux)
    target: bin/pilot

  - name: windows
    type: content/binary
    license: Apache Version 2
    run:
      - $(build-windows)
    target: bin/pilot

  - name: testpack
    type: content/test
    target: ./testpk
...