---
env:
  # the application version
  APP_VERSION: 0.0.4
  # a unique build number
  BUILD_VERSION: ${APP_VERSION}-${ARTISAN_REF}
  ART_GROUP: lib
  APP_NAME: telemetry
  CGO_ENABLED: 0
  GOARCH: amd64
  ART_REG: artr.gdn

labels:
  author: gatblau.org
  application: Pilot
  product: Onix Configuration Manager
  description: Onix agent for managing remote host configuration
  architecture: AMD64

functions:
  - name: set-version
    description: set new version reference
    run:
      - bash -c "echo ${ARTISAN_REF} > ${PWD}/version"

  - name: build
    description: builds the host telemetry for the linux platform
    env:
      GOOS: linux
    run:
      - $(set-version)
      - rm -rf install/telemetry && install/telem.yaml
      - cp telem.yaml install/
      - go build -ldflags="-X 'github.com/gatblau/onix/telemetry/collector.Version=${BUILD_VERSION}'" -o install/telemetry -v
      - art build . -t ${ART_REG}/${ART_GROUP}/${APP_NAME}:$((cat ./version)) -p linux
      - art tag ${ART_REG}/${ART_GROUP}/${APP_NAME}:$((cat ./version)) ${ART_REG}/${ART_GROUP}/${APP_NAME}:latest

  - name: push
    description: push to Artisan registry
    run:
      - art push ${ART_REG}/${ART_GROUP}/${APP_NAME}:$((cat ./version))
      - art push ${ART_REG}/${ART_GROUP}/${APP_NAME}:latest

  - name: manifest
    run:
      - rm -f ./manifest.md
      - art manifest ${ART_REG}/${ART_GROUP}/${APP_NAME}:$((cat ./version)) -o=mdf

  - name: all
    description: run new version, build and push
    run:
      - $(set-version)
      - $(build)
      - $(manifest)
      - $(push)

profiles:
  - name: linux
    default: true
    type: content/binary
    license: Apache Version 2
    target: install
...