---
labels:
  author: onix@gatblau.org
  application: Onix Pilot Control Event Receiver using MongoDb
  description: A syslog events receiver for Pilot Control, that uses MongoDb as the data store

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  REPO_NAME: quay.io/gatblau
  APP_NAME: pilotctl-evr-mongodb
  # the application version
  APP_VERSION: 0.0.4
  # a unique build number
  BUILD_VERSION: ${APP_VERSION}-${ARTISAN_REF}

functions:
  - name: swagen
    description: generates/refreshes the OpenAPI specifications for PilotCtl's Mongo Event Receiver HTTP API
    run:
      - swag init -d ./ -g handlers.go  --parseDependency types/*.go

  - name: build-linux
    description: builds MongoDb event receiver for PilotCtl binary file for the linux platform
    env:
      GOOS: linux
    run:
      - go fmt
      - go build -ldflags="-X 'github.com/gatblau/onix/piloctl/receivers/mongo/core.Version=${BUILD_VERSION}'" -o bin/mongo-evr -v

  - name: release
    description: builds and publishes MongoDb event reciver for Pilot Control image
    run:
      - $(build-linux)
      - docker build -t ${REPO_NAME}/${APP_NAME}:${BUILD_VERSION} .
      - docker tag ${REPO_NAME}/${APP_NAME}:${BUILD_VERSION} ${REPO_NAME}/${APP_NAME}:latest
      - docker push ${REPO_NAME}/${APP_NAME}:${BUILD_VERSION}
      - docker push ${REPO_NAME}/${APP_NAME}:latest
...