package features;

public class Key {
    public static final String RESPONSE = "response";
    public static final String BASE_URL = "base_url";
    public static final String ITEM_URL = "item_url";
    public static final String CLEAR_URL = "clear_url";
    public static final String EXCEPTION = "exception";
    public static final String ITEM_ONE_KEY = "item_one_key";
    public static final String ITEM_TWO_KEY = "item_two_key";
    public static final String PAYLOAD = "payload";
    public static final String ITEM_TYPE_URL = "item_type_url";
    public static final String LINK_URL = "link_url";
    public static final String CONGIG_ITEM_TYPE_ID = "config_item_type_id";
    public static final String CONGIG_ITEM_TYPE_KEY = "config_item_type_key";
    public static final String CONFIG_ITEM_TAG = "config_item_tag";
    public static final String CONFIG_ITEM_UPDATED_FROM = "config_item_updated_from";
    public static final String CONFIG_ITEM_UPDATED_TO = "config_item_updated_to";
    public static final String LINK_KEY = "link_key";
    public static final String ENDPOINT_URI = "endpoint_uri";
    public static final String ITEM_KEY = "item_key";
    public static final String LINK_ONE_KEY = "link_one_key";
    public static final String LINK_TYPE_URL = "link_type_url";
    public static final String CONGIG_LINK_TYPE_KEY = "link_type_key";
    public static final String LINK_RULE_URL = "link_rule_url";
    public static final String LINK_RULE_KEY = "link_rule_key";
    public static final String INVENTORY_FILE = "inventory_file";
    public static final String INVENTORY_KEY = "inventory_key";
    public static final String INVENTORY_URL = "inventory_url";
    public static final String SNAPSHOT_CREATE_URL = "snapshot_create_url";
    public static final String SNAPSHOT_UPDATE_URL = "snapshot_update_url";
    public static final String SNAPSHOT_CREATE_PAYLOAD = "create_snapshot_payload";
    public static final String SNAPSHOT_UPDATE_PAYLOAD = "update_snapshot_payload";
    public static final String SNAPSHOT_ITEM_ROOT_KEY = "snapshot_item_root_key";
    public static final String SNAPSHOT_LABEL = "snapshot_label";
    public static final String SNAPSHOT_DELETE_URL = "snapshot_delete_url";
    public static final String SNAPSHOT_LIST_URL = "snapshot_list_url";
    public static final String SNAPSHOT_TREE_URL = "snapshot_tree_url";
    public static final String INVENTORY_LABEL = "inventory_label";
}
