---
input:
  var:
    - name: LS_DIR
      description: the directory to list
      default: /tmp
    - name: RSYSLOG_ENABLED
      description: Set to true to enable rsyslog forwarding to Pilot, false to disable
      default: true

functions:
  - name: list
    description: runs a list command on a folder
    export: true
    runtime: ubi-min
    run:
      - ls -la ${LS_DIR}
    input:
      var:
        - LS_DIR

  - name: printenv
    description: prints the current env vars
    export: true
    runtime: ubi-min
    run:
      - printenv

  - name: cpu
    description: gets host CPU information (only works on linux)
    export: true
    runtime: ubi-min
    run:
      - cat /proc/cpuinfo

  - name: partitions
    description: gets host partitions information (only works on linux)
    export: true
    runtime: ubi-min
    run:
      - cat /proc/partitions

  - name: raise-events
    description: Raises some sample events directly to Pilot
    export: true
    runtime: ubi-min
    run:
      - sh ./raise-event.sh

  - name: rsyslog-pilot
    description: Enables or disables rsyslog forward to Pilot
    export: true
    runtime: ubi-min
    run:
      - sh ./rsyslog-set.sh ${RSYSLOG_ENABLED}
    input:
      var:
        - RSYSLOG_ENABLED
...
