---
labels:
  author: onix@gatblau.org
  application: Onix Pilot Host Control Service
  description: An HTTP API for managing Host Pilot agents

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  REPO_NAME: quay.io/gatblau
  APP_NAME: pilotctl
  # the application version
  APP_VERSION: 0.0.4
  # a unique build number
  BUILD_VERSION: ${APP_VERSION}-${ARTISAN_REF}

functions:
  - name: build-linux
    description: builds the PilotCtl binary file for the linux platform
    env:
      GOOS: linux
    run:
      - go fmt
      - go build -ldflags="-X 'github.com/gatblau/onix/piloctl/core.Version=${BUILD_VERSION}'" -o bin/pilotctl -v

  - name: swagen
    description: generates/refreshes the OpenAPI specifications for PilotCtl's HTTP API
    run:
      - swag init -d ./ -g ./handlers.go  --parseDependency types/*.go

  - name: release
    description: builds and publishes the Pilot Control image
    run:
      - $(build-linux)
      - docker build -t ${REPO_NAME}/${APP_NAME}:${BUILD_VERSION} .
      - docker tag ${REPO_NAME}/${APP_NAME}:${BUILD_VERSION} ${REPO_NAME}/${APP_NAME}:latest
      - docker push ${REPO_NAME}/${APP_NAME}:${BUILD_VERSION}
      - docker push ${REPO_NAME}/${APP_NAME}:latest

  - name: build-image-local
    description: builds and publishes the Pilot Control image
    run:
      - $(build-linux)
      - docker build -t ${REPO_NAME}/${APP_NAME}:${BUILD_VERSION} .
      - docker tag ${REPO_NAME}/${APP_NAME}:${BUILD_VERSION} ${REPO_NAME}/${APP_NAME}:latest

  - name: up
    run:
      - docker run --name rem -d -p 8080:8080 ${REPO_NAME}/${APP_NAME}
...