INSERT INTO item_type(id, name, description) VALUES (1, 'Physical Host', 'Bare metal server running an hypervisor host');
INSERT INTO item_type(id, name, description) VALUES (2, 'Virtual Host', 'A guest Virtual Machine host.');
INSERT INTO item_type(id, name, description) VALUES (3, 'Host Group', 'A group of hosts for configuration management purposes.');
INSERT INTO item_type(id, name, description) VALUES (4, 'Inventory', 'A set of host groups for deployment purposes.');
INSERT INTO item_type(id, name, description) VALUES (5, 'Operating System', 'The Operating System running on a host.');
INSERT INTO item_type(id, name, description) VALUES (6, 'Management Agent', 'A software management agent running on a host.');
INSERT INTO item_type(id, name, description) VALUES (7, 'Application Server', 'An application server running on a host.');
INSERT INTO item_type(id, name, description) VALUES (8, 'Database Server', 'A database server running on a host.');
INSERT INTO item_type(id, name, description) VALUES (8, 'Message Broker', 'A message broker running on a host.');
INSERT INTO item_type(id, name, description) VALUES (9, 'OCP Tenant', 'A tenant space on the OpenShift Container Platform.');
INSERT INTO item_type(id, name, description) VALUES (10, 'OCP Project', 'A Kubernetes namespace within a tenant space in the OpenShift Container Platform.');
INSERT INTO item_type(id, name, description) VALUES (11, 'Physical Router', '');
INSERT INTO item_type(id, name, description) VALUES (12, 'Virtual Router', '');
INSERT INTO item_type(id, name, description) VALUES (13, 'Physical Firewall', '');
INSERT INTO item_type(id, name, description) VALUES (14, 'Virtual Firewall', '');
INSERT INTO item_type(id, name, description) VALUES (15, 'Virtual Local Area Network', '');
INSERT INTO item_type(id, name, description) VALUES (16, 'AWS Security Zone', '');