functions:
  - name: install
    description: install OpenTelemetry collector for managed hosts.
    export: true
    run:
      - sh -c './install.sh'
  - name: uninstall
    description: uninstall OpenTelemetry collector for managed hosts.
    export: true
    run:
      - sh -c './uninstall.sh'
  - name: start
    description: start the OpenTelemetry service for managed hosts.
    export: true
    run:
      - sh -c 'sudo systemctl enable --now telemetry'

  - name: stop
    description: stop the OpenTelemetry service for managed hosts.
    export: true
    run:
      - sh -c 'sudo systemctl stop telemetry'      