---
input:
  var:
    - name: OX_WAPI_URI
      description: Onix wapi uri.
      required: true
      type: string
    - name: OX_WAPI_INSECURE_SKIP_VERIFY
      description: Whether to skip SSL insecure access to onix wapi api.
      default: true
      required: true
      type: string
  secret:
    - name: OBJECT_STORE_ACCESS_KEY
      description: Object storage access key or user name that will be used to connect remote object store
      required: true
      type: string
    - name: OBJECT_STORE_SECRET_KEY
      description: Object storage secret key or password that will be used to connect remote object store
      required: true
      type: string
    - name: OX_WAPI_USER
      description: Onix wapi user name.
      required: true
      type: string
    - name: OX_WAPI_PWD
      description: Onix wapi password.
      required: true
      type: string      
functions:
  - name: install
    description: Start the host-runner application
    export: true
    run:
      - sh -c './install.sh'
    input:
      var:
        - OX_WAPI_URI
        - OX_WAPI_INSECURE_SKIP_VERIFY
      secret:
        - OBJECT_STORE_ACCESS_KEY
        - OBJECT_STORE_SECRET_KEY
        - OX_WAPI_USER
        - OX_WAPI_PWD
  - name: uninstall
    description: Stop the host-runner application
    export: true
    run:
      - sh -c './uninstall.sh'