---
labels:
  author: onix@gatblau.org
  application: Host runner
  description: The environment to run artison flows
  architecture: AMD64

env:
  ART_GROUP: aps
  APP_NAME: host-runner
  CGO_ENABLED: 0
  GOARCH: amd64
  APP_VERSION: 0.0.4
  BUILD_VERSION: ${APP_VERSION}-${ARTISAN_REF}

profiles:
  - name: build-push
    default: true
    application: host-runner
    type: content/binary
    license: Apache Version 2
    labels:
      platform: linux
    env:
      GOOS: linux
    target: binary

functions:
  - name: go-build
    description: builds the Artisan CLI for the linux platform
    env:
      GOOS: linux
    run:
      - rm -f binary/host-runner     
      - go build -ldflags="-X 'github.com/gatblau/onix/artisan/core.Version=${BUILD_VERSION}'" -o binary/${APP_NAME} -v

  - name: set-version
    description: set new version reference
    run:
      - bash -c "echo ${ARTISAN_REF} > ${PWD}/version"

  - name: build
    description: build Artisan package
    run:
      - $(go-build)
      - art build . -t ${ART_REG}/${ART_GROUP}/${APP_NAME}:$((cat ./version)) -p build-push
      - art tag ${ART_REG}/${ART_GROUP}/${APP_NAME}:$((cat ./version)) ${ART_REG}/${ART_GROUP}/${APP_NAME}:latest

  - name: push
    description: push to Artisan registry
    run:
      - art push ${ART_REG}/${ART_GROUP}/${APP_NAME}:$((cat ./version))
      - art push ${ART_REG}/${ART_GROUP}/${APP_NAME}:latest

  - name: all
    description: run new version, build and push
    run:
      - $(set-version)
      - $(build)
      - $(manifest)
      - $(push)
      - rm -f binary/${APP_NAME}

  - name: swagen
    description: generates/refreshes the OpenAPI specifications for Artisan's HTTP API
    run:
      - swag init -d ./ -g handlers.go

  - name: manifest
    run:
      - rm -f ./manifest.md
      - art manifest ${ART_REG}/${ART_GROUP}/${APP_NAME}:$((cat ./version)) -o=mdf      
...