#
# Sentinel - Copyright (c) 2019 by www.gatblau.org
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied.
# See the License for the specific language governing permissions and limitations under the License.
#
# Contributors to this project, hereby assign copyright in this code to the project,
# to be licensed under the same terms as the rest of the code.
#
# Virtual Machine for testing the Sentinel integration with
# the Apache Kafka message broker
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.6"
  config.vm.box_check_update = true
  # makes kafka/zookeper ports available on the host VM
  config.vm.network "forwarded_port", guest: 2181, host: 2181, protocol: "tcp", auto_correct: true
  config.vm.network "forwarded_port", guest: 9092, host: 9092, protocol: "tcp", auto_correct: true
end
