// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "gatblau",
            "url": "http://onix.gatblau.org/",
            "email": "onix@gatblau.org"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Checks that Artie's HTTP server is listening on the required port.\nUse a liveliness probe.\nIt does not guarantee the server is ready to accept calls.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "General"
                ],
                "summary": "Check that Artie's HTTP API is live",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admission": {
            "put": {
                "description": "inform pilotctl to accept management connections coming from a host pilot agent\nadmitting a host also requires associating the relevant logistic information such as org, area and location for the host",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Admission"
                ],
                "summary": "Admits a host into service",
                "parameters": [
                    {
                        "description": "the required admission information",
                        "name": "command",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Admission"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/area/{area}/location": {
            "get": {
                "description": "Get a list of locations setup in an area",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logistics"
                ],
                "summary": "Get Locations in an Area",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the unique id for area under which locations are defined",
                        "name": "area",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cmd": {
            "get": {
                "description": "get a list of all command definitions",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Command"
                ],
                "summary": "Get all Command definitions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "creates a new or updates an existing command definition",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Command"
                ],
                "summary": "Create or Update a Command",
                "parameters": [
                    {
                        "description": "the command definition",
                        "name": "command",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Cmd"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cmd/{name}": {
            "get": {
                "description": "get a specific a command definition",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Command"
                ],
                "summary": "Get a Command definition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the unique name for the command to retrieve",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/host": {
            "get": {
                "description": "Returns a list of remote hosts",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Host"
                ],
                "summary": "Get All Hosts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the organisation group key to filter the query",
                        "name": "og",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "the organisation key to filter the query",
                        "name": "or",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "the area key to filter the query",
                        "name": "ar",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "the location key to filter the query",
                        "name": "lo",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "a pipe | separated list of labels associated to the host(s) to retrieve",
                        "name": "label",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/job": {
            "get": {
                "description": "Returns a list of jobs filtered by the specified logistics tags",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Get Jobs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "the unique identifier (number) of the job batch to retrieve",
                        "name": "bid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "the organisation group key to filter the query",
                        "name": "og",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "the organisation key to filter the query",
                        "name": "or",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "the area key to filter the query",
                        "name": "ar",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "the location key to filter the query",
                        "name": "lo",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "create a new job for execution on one or more remote hosts",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Create a Job",
                "parameters": [
                    {
                        "description": "the information required to create a new job",
                        "name": "command",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.JobBatchInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/job/batch": {
            "get": {
                "description": "Returns a list of jobs batches with various filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Get Job Batches",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the name of the batch as in name% format",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "the creator of the batch",
                        "name": "owner",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "a pipe | separated list of labels associated to the batch",
                        "name": "label",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "the time from which to get batches (format should be dd-MM-yyyy)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "the time to which to get batches (format should be dd-MM-yyyy)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/org-group": {
            "get": {
                "description": "Get a list of organisation groups",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logistics"
                ],
                "summary": "Get Organisation Groups",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/org-group/{org-group}/area": {
            "get": {
                "description": "Get a list of areas setup in an organisation group",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logistics"
                ],
                "summary": "Get Areas in Organisation Group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the unique id for organisation group under which areas are defined",
                        "name": "org-group",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/org-group/{org-group}/org": {
            "get": {
                "description": "Get a list of organisations setup in an organisation group",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logistics"
                ],
                "summary": "Get Organisations in Organisation Group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the unique id for organisation group under which organisations are defined",
                        "name": "org-group",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/package": {
            "get": {
                "description": "get a list of packages in the backing Artisan registry",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Registry"
                ],
                "summary": "Get Artisan Packages",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/package/{name}/api": {
            "get": {
                "description": "get a list of exported functions and inputs for the specified package",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Registry"
                ],
                "summary": "Get the API of an Artisan Package",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the fully qualified name of the artisan package having the required API",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "data.File": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "the file content",
                    "type": "string"
                },
                "description": {
                    "description": "a description of the intended use of this file",
                    "type": "string"
                },
                "name": {
                    "description": "the unique reference for the file",
                    "type": "string"
                },
                "path": {
                    "description": "path to the file within the Artisan registry",
                    "type": "string"
                }
            }
        },
        "data.Input": {
            "type": "object",
            "properties": {
                "file": {
                    "description": "reguired by configuration files",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.File"
                    }
                },
                "key": {
                    "description": "required PGP keys",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.Key"
                    }
                },
                "secret": {
                    "description": "required string value secrets",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.Secret"
                    }
                },
                "var": {
                    "description": "required variables",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.Var"
                    }
                }
            }
        },
        "data.Key": {
            "type": "object",
            "properties": {
                "aggregate": {
                    "description": "indicates if this key should be aggregated with other keys",
                    "type": "boolean"
                },
                "description": {
                    "description": "a description of the intended use of this key",
                    "type": "string"
                },
                "name": {
                    "description": "the unique reference for the PGP key",
                    "type": "string"
                },
                "package_group": {
                    "description": "the artisan package group used to select the key",
                    "type": "string"
                },
                "package_name": {
                    "description": "the artisan package name used to select the key",
                    "type": "string"
                },
                "path": {
                    "description": "the path to the key in the Artisan registry",
                    "type": "string"
                },
                "private": {
                    "description": "indicates if the referred key is private or public",
                    "type": "boolean"
                },
                "value": {
                    "description": "the key content",
                    "type": "string"
                }
            }
        },
        "data.Secret": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "a description of the intended use or meaning of this secret",
                    "type": "string"
                },
                "name": {
                    "description": "the unique reference for the secret",
                    "type": "string"
                },
                "value": {
                    "description": "the value of the secret",
                    "type": "string"
                }
            }
        },
        "data.Var": {
            "type": "object",
            "properties": {
                "default": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "required": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "types.Admission": {
            "type": "object",
            "properties": {
                "area": {
                    "type": "string"
                },
                "host_uuid": {
                    "type": "string"
                },
                "label": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "location": {
                    "type": "string"
                },
                "org": {
                    "type": "string"
                },
                "org_group": {
                    "type": "string"
                }
            }
        },
        "types.Cmd": {
            "type": "object",
            "properties": {
                "containerised": {
                    "description": "run command in runtime",
                    "type": "boolean"
                },
                "description": {
                    "description": "description of the command",
                    "type": "string"
                },
                "function": {
                    "description": "the function in the package to call",
                    "type": "string"
                },
                "input": {
                    "description": "the function input information",
                    "$ref": "#/definitions/data.Input"
                },
                "key": {
                    "description": "the natural key uniquely identifying the command",
                    "type": "string"
                },
                "package": {
                    "description": "the package to use",
                    "type": "string"
                },
                "pwd": {
                    "description": "the package registry password",
                    "type": "string"
                },
                "user": {
                    "description": "the package registry user",
                    "type": "string"
                },
                "verbose": {
                    "description": "enables verbose output",
                    "type": "boolean"
                }
            }
        },
        "types.JobBatchInfo": {
            "type": "object",
            "properties": {
                "fx_key": {
                    "description": "the unique key of the function to run",
                    "type": "string"
                },
                "fx_version": {
                    "description": "the version of the function to run",
                    "type": "integer"
                },
                "host_uuid": {
                    "description": "the universally unique host identifier created by pilot",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "label": {
                    "description": "one or more search labels",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "the name of the batch (not unique, a user-friendly name)",
                    "type": "string"
                },
                "notes": {
                    "description": "any relevant notes for the batch (not mandatory)",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.4",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Pilot Control",
	Description: "Onix Config Manager Control Service for Pilot Host agent",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
